name: TESTE ACTIONS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Inicio
        run: echo "RUNNER INICIOU"

      - name: Sistema
        run: |
          echo "Sistema:"
          uname -a
          echo "Data:"
          date

      - name: Fim
        run: echo "RUNNER FUNCIONOU"